name: Node.js Monorepo Build and Test

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install npm dependencies
    - name: Install
      run: npm install -w source/ -w utility/

    # Build for bundle
    - name: Build
      run: npm run build -w source/

    # Uni test
    - name: Test
      run: npm test -w source/ -w utility/
